#pragma once
#include <cstdint>
#include <string>

namespace CUI {

enum class PropertyId : uint16_t {
    None = 0,
    Width,
    Height,
    MinWidth,
    MinHeight,
    Margin,
    Padding,
    Visibility,
    IsEnabled,
    Opacity,
    CornerRadius,
    BorderThickness,
    FlexGrow,
    Align,
    AlignHorizontal,
    AlignVertical,
    Orientation,
    Gap,
    ItemWidth,
    ItemHeight,
    LastChildFill,
    Rows,
    Columns,
    ClipToBounds,
    CanvasLeft,
    CanvasTop,
    CanvasRight,
    CanvasBottom,
    GridColumn,
    GridRow,
    GridColumnSpan,
    GridRowSpan,
    Dock,
    Text,
    Placeholder,
    FontFamily,
    FontSize,
    FontWeight,
    ToolTip,
    Icon,
    Focused,
    BackgroundToken,
    HoverBackgroundToken,
    PressedBackgroundToken,
    DisabledBackgroundToken,
    BorderToken,
    FocusedBorderToken,
    ColorToken,
    SecondaryColorToken,
    PlaceholderColorToken,
    SelectedBackgroundToken,
    HeaderBackgroundToken,
    PaneBackgroundToken,
    IndicatorColorToken,
    DropdownBackgroundToken,
    SelectedItemBackgroundToken,
    FillColorToken,
    TrackColorToken,
    ActiveTrackColorToken,
    ThumbColorToken,
    OnColorToken,
    OffColorToken,
    KnobColorToken,
    CheckedBackgroundToken,
    AccentColorToken,
    ActiveColorToken,
    UnderlineColorToken,
    ActiveUnderlineColorToken,
    ActiveTabBackgroundToken,
    InactiveTabBackgroundToken,
    GridLineBrushToken,
    TitleColorToken,
    MessageColorToken,
    CaretColorToken,
    Background,
    BorderBrush,
    HoverBackground,
    PressedBackground,
    Color,
    Items,
    ControlValue,
    CheckState,
    IsThreeState,
    IsIndeterminate,
    IsOn,
    DateStr,
    TimeStr,
    SelectedColor,
    CurrentPage,
    TotalPages,
    Minimum,
    Maximum,
    Step,
    IsReadOnly,
    IsClearEnabled,
    Count
};

const char* PropertyIdToName(PropertyId id);
PropertyId PropertyIdFromName(const char* name);
PropertyId PropertyIdFromName(const std::string& name);

} // namespace CUI
